---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nopdb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard

