---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc-np
  labels:
    app: jenkins
    purpose: svcdemo
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30001