---
apiVersion: v1
kind: Service
metadata: 
  labels:
    name: nginx-svc-nodeport
    purpose: to connect to multiple nodes
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32024