---
apiVersion: v1
kind: Service
metadata: 
  labels:
    name: service-file
    purpose: to connect to servcie port
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
       
