---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-sample
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxc
          image: nginx:1.25
    
  
