---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: mutli-webserver
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: tomcat
    image: tomcat:jdk17
    resources:
      limits:
        memory: "128Mi"
        cpu: "600m"
    ports:
      - containerPort: 8080
 
