---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: webserver
  labels:
    name: nginx-server 
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    metadata:
      labels:
        name: nginxdemo
    spec:
      template:
        metadata:
          labels:
            name: batch
        spec:
          restartPolicy: OnFailure
          containers:
            - name: batchdemo
              image: alpine
              command:
                - sleep
                - 10s
        


 
              