---
apiVersion: v1
kind: Pod
metadata:
  name: cm-s-demo
  labels:
    name: demo
spec:
  containers:
  - name: experiment
    image: alpine
    resources:
      limits:
        memory: "50Mi"
        cpu: "150m"
    command:
      - sleep
      - 1d
    envFrom:
      - configMapRef:
          name: userinfo-cm
      - secretRef:
          name: password-secret
    
