---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
  labels:
    name: webserver-tomcat
    release: v1.0
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      name: tomcat
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat-jdk17
          ports:
            - containerPort: 8080
              protocol: TCP


