---
apiVersion: v1
kind: Pod
metadata:
  name: nop-app
  labels:
    name: app
    purpose: learning
spec:
  containers:
    - name: nop
      image: alpine:3
      env:
        - name: learning
      # args:
      #   - "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.4/nopCommerce_4.60.4_NoSource_linux_x64.zip"
      # command:
      #   - dotnet
      #   - Nop.web.dll
      ports:
        - containerPort: 80
          protocol: TCP
        
