---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nop-app
  labels:
    app: nopcommerce
  namespace: dev
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: nopcommerce
  template:
    metadata:
      labels:
        app: nopcommerce
    spec:
      containers:
        - name: nop-commerce
          image: abhishek08tcs/nopcommerce:51
          env:
            - name: purpose
              value: learning
          ports:
            - containerPort: 80
              protocol: TCP
            