---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata: 
  name: nop-pod
  namespace: dev
  labels:
    app: nop
spec:
  containers:
    - name: nop-commerce
      image: abhishek08tcs/nopcommerce:51
      env:
        - name: purpose
          value: learning
      ports:
        - containerPort: 80
          protocol: TCP